[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
# on_ft = ['go', 'javascript', 'typescript', 'vue', 'jsx', 'tsx', 'proto', 'sql']

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf', 'tfvars', 'tfstate']

[[plugins]]
repo = 'jjo/vim-cue'
on_ft = ['cue']

[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = ['go']

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'

[[plugins]]
repo = 'petertriho/nvim-scrollbar'

[[plugins]]
repo = 'dinhhuy258/git.nvim'

[[plugins]]
repo = 'akinsho/git-conflict.nvim'

[[plugins]]
repo = 'rachartier/tiny-inline-diagnostic.nvim'
