[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'ts'

[[plugins]]
repo = 'fatih/vim-hclfmt'
on_ft = ['hcl', 'tf']
