[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'neomru.vim'
hook_post_source = '''
call denite#custom#option('_', 'mode', 'normal')
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs', [ '.git/', 'node_modules/', '__pycache__/', 'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_ft = ['go', 'rb', 'py', 'ts', 'js']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'ts'

[[plugins]]
repo = 'fatih/vim-hclfmt'
on_ft = ['hcl', 'tf']
